title:             Fresh - Modern Bulma Ecommerce App and Dashboard
email:             your-email@example.com
description: ""
author: ""

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""
