title:             Fresh - Modern Bulma Ecommerce App and Dashboard
email:             your-email@example.com
description: ""
author: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

exclude:
  - LICENSE
  - README.md
  - fresh.gif

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""
